// mod day1;
// mod day2;
// mod day3;
// mod day4;
// mod day5;
// mod day6;
// mod day7;
// mod day8;
// mod day9;
mod day10;

fn main() {
    // use day1::solve_part_1 as solve_day_1_part_1;
    // use day1::solve_part_2 as solve_day_1_part_2;
    // use day2::solve_part_1 as solve_day_2_part_1;
    // use day2::solve_part_2 as solve_day_2_part_2;
    // use day3::solve_part_1 as solve_day_3_part_1;
    // use day3::solve_part_2 as solve_day_3_part_2;
    // use day4::solve_part_1 as solve_day_4_part_1;
    // use day4::solve_part_2 as solve_day_4_part_2;
    // use day5::solve_part_1 as solve_day_5_part_1;
    // use day5::solve_part_2 as solve_day_5_part_2;
    // use day6::solve_part_1 as solve_day_6_part_1;
    // use day6::solve_part_2 as solve_day_6_part_2;
    // use day7::solve_part_1 as solve_day_7_part_1;
    // use day7::solve_part_2 as solve_day_7_part_2;
    // use day8::solve_part_1 as solve_day_8_part_1;
    // use day8::solve_part_2 as solve_day_8_part_2;
    // use day9::solve_part_1 as solve_day_9_part_1;
    // use day9::solve_part_2 as solve_day_9_part_2;
    use day10::solve_part_1 as solve_day_10_part_1;
    // use day10::solve_part_2 as solve_day_10_part_2;

    // solve_day_1_part_1();
    // solve_day_1_part_2();
    // solve_day_2_part_1();
    // solve_day_2_part_2();
    // solve_day_3_part_1();
    // solve_day_3_part_2();
    // solve_day_4_part_1();
    // solve_day_4_part_2();
    // solve_day_5_part_1();
    // solve_day_5_part_2();
    // solve_day_6_part_1();
    // solve_day_6_part_2();
    // solve_day_7_part_1();
    // solve_day_7_part_2();
    // solve_day_8_part_1();
    // solve_day_8_part_2();
    // solve_day_9_part_1();
    // solve_day_9_part_2();
    solve_day_10_part_1();
    // solve_day_10_part_2();
}
